#!/usr/bin/env python3

import os,sys
import subprocess


def main():
    root, subdirs, files = next(os.walk("."))
    challs = []
    options = " ".join(sys.argv[1:])
    for subdir in sorted(subdirs):
        print(f"===============")
        print(f"Building {subdir[3:]}")
        print(f"===============")
        subprocess.call(f"docker build {options} -t {subdir[3:]} {subdir}", shell=True)

if __name__ == '__main__':
    main()


